### ISSUE TITLE
Add back `min` and `max` schema parameters

### ISSUE THREAD

**Issue by tingerrr** [typst-community/valkyrie#10]
Previously the `number`, `integer`, `float`, `string`, and `array` schemas had the parameters `min` and `max`.

I propose adding these back, those range checks are fairly convenient, especially combined with `z.<schema>.with(min: ...)` for schema adaption. The main downside of not having them now is that nested schema validation cannot perform easy length checks.

**Comment by JamesxX** [comment]
As mentioned on discord, definitely agree. The last version where it existed was here:
https://github.com/typst-community/valkyrie/blob/efd9a08e01a8763fb54386242d3fedcb9ec27586/src/types/array.typ#L61-L83

I'll make a branch and see about bringing this sort of way of handling it back
