### ISSUE TITLE
Handle `default` in case of `auto`, not `none`

### ISSUE THREAD

**Issue by tingerrr** [typst-community/valkyrie#14]
Currently, the `default` in `base-type` is used if `it == none or == type(none)`, ideally this should happen when it is `auto`, as `none` means an explicit opt, out in most cases.

I'm unsure whether this is always a good idea, this likely interferes with `optional: true` too in some way.

**Comment by JamesxX** [comment]
I agree that it should be `auto`, but `none` is what is being used the represent absence. This will need quite a bit of time to see what this change might break, but I'd be more than willing to have default work as you suggest if we don't regress too much :P

**Comment by tingerrr** [comment]
Yeah, I labeled it as question, precisely because of this ambiguity.

Perhaps we should track internally whether a value was absent or not without just treating it as it to `none`, most compound types use `auto` for this.

Especially for more complicated schemas like that of a stroke, the absence of a field doesn't mean `none`, but rather whatever default is used in Typst, for exmaple `paint: black, thickness: 1pt`.
