### ISSUE TITLE
Allow default values to use other values

### ISSUE THREAD

**Issue by jneug** [typst-community/valkyrie#29]
I would like to be able to set the default value of one value to be the same as the value of another argument, or use that value somehow. 

For example, if I wanted to create a `create-theme` function that creates a color theme with a primary, secondary and tertiary color:
```typst
#{
 let theme-schema = t.dictionary((
    primary: t.color(),
    secondary: t.color(optional: true),
    tertiary: t.color(optional: true),
  ))

  let create-theme(primary, ..args) = {
    let theme = t.parse(
      (
        primary: primary,
        ..args.named(),
      ),
      theme-schema,
    )
    if theme.secondary == none {
      theme.secondary = theme.primary.rotate(120deg)
    }
    if theme.tertiary == none {
      theme.tertiary = theme.primary.rotate(240deg)
    }
    return theme
  }

  create-theme(rgb("#ff2f93"))
}
```

I need to check each optional value and set it to a color that is based on the mandatory primary color if none was given. It would be nice to define this kind of default value in the schema itself.

Maybe some kind of "`pos-post-transform`" could be introduced that runs after all values have been parsed and receives the result of the parsing. Something like this:
```typst
#{
  let theme-schema = t.dictionary((
    primary: t.color(),
    secondary: t.color(
      optional: true,
      post-post-transform: (self, it, result) => {
        if it == none {
          result.primary.rotate(120deg)
        } else {
          it
        }
      },
    ),
    tertiary: t.color(
      optional: true,
      post-post-transform: (self, it, result) => {
        if it == none {
          result.primary.rotate(240deg)
        } else {
          it
        }
      },
    ),
  ))
}
```

**Comment by JamesxX** [comment]
That's a trickier ask, I think the idiomatic way would be to do a post-transform at the dictionary level rather than on the colour schema

**Comment by jneug** [comment]
🤦🏻 That makes sense. Don't know why I didn't think of that.

I can just put a `post-transform` on the outermost type and can be done with this:
```typst
  let theme-schema = t.dictionary(
    (
      primary: t.color(),
      secondary: t.color(optional: true),
      tertiary: t.color(optional: true),
    ),
    post-transform: (_, it) => {
      if it.secondary == none {
        it.secondary = theme.primary.rotate(120deg)
      }
      if it.tertiary == none {
        it.tertiary = theme.primary.rotate(240deg)
      }
      return it
    },
  )
```
