### ISSUE TITLE
Should coercions respect `optional: true`?

### ISSUE THREAD

**Issue by jneug** [typst-community/valkyrie#33]
Not sure if this is intended, but currently coercions will panic if a value is none, which can happen with `optional: true` set. 

I think it would be more intuitive, if a coercion respected the `optional` setting and returned `none`, if the key was not present.

For example, the `array` coercion would look like this: 
```typst
#let array(self, it) = {
  if self.optional and it == none {
    return none
  }
  if (type(it) != type(())) {
    return (it,)
  }
  it
}
```

**Comment by JamesxX** [comment]
Good catch! I'm hoping to be able to put some time into this package this weekend and get the next version published.

**Comment by JamesxX** [comment]
I was putting some thought into this and the conclusion I come to is that there's no general solution. I'll close this for now but I've been staring at it for the past half hour and can't see a good way of doing it.
