### ISSUE TITLE
Conditional dictionary assertions for elements

### ISSUE THREAD

**Issue by TimeTravelPenguin** [typst-community/valkyrie#50]
Is it possible to define a schema to assert something analogous to the following:
```typ
#let schema = z.dictionary((
    current: z.integer(min: 0),
    maximum: z.integer(min: 0),
))
```
such that it is asserted that `current` <= `maximum`?

In general, can we write a dictionary schema that has assertions defined using the dictionary values? I have a use case where I have several keys that have an exclusive relationship -- depending on optional arguments, different assertions need to be affirmed, each on different arguments.

Normally, this would be outside the scope of the schema, but the relationship is one such that it is a little more sensical (and convenient) to have it asserted by the schema.

Edit:

I was planning on just making a function analogous to:
```typst
#let make-schema(max) = z.dictionary((
    current: z.integer(min: 0, max: max),
))
```
However, this is a bit awkward since now I don't have the maximum stored on my object, which is needed. And, if I add it to my object, then, when I parse my object, I provide the maximum both on the parsed object _and_ the schema. My exact use case is a bit more awkward, but this is the general idea.

That is, the full example would be:
```typst
#let make-schema(max) = z.dictionary((
    current: z.integer(min: 0, max: max),
    maximum: z.integer(min: 0),
))

#let fun(current, max) = {
    let schema = make-schema(max)

    return z.parse((
        current: current,
        max: max
    ),
    schema)
}
```

My problem with this, besides the awkwardness, is that I _do not_ know `max` ahead of time. So, this doesn't actually work in my actual use case (though, it works in this analogy).

**Comment by tingerrr** [comment]
Yes, you can, although it is not well documented, you can add assertions to a schema like so (note the extra comma because an array is expected):
```typ
#import "@preview/valkyrie:0.2.1" as z

#let assertion-min-max-ordering = (
  condition: (self, it) => it.max >= it.min,
  message: (self, it) => "Max must be greater than or equal to min, got: `" + repr(it) + "`",
)

#let schema = z.dictionary(
  (min: z.integer(), max: z.integer()),
  assertions: (assertion-min-max-ordering,),
)

// ok
#z.parse(
  (min: 5, max: 10),
  schema,
)

// fail
#z.parse(
  (min: 10, max: 5),
  schema,
)
```

Although I'd have to look how this interacts with coercions and pre-/post-transform steps.

**Comment by TimeTravelPenguin** [comment]
Ah, ok sweet!

I wasn't sure if this was the intended way or not since the docs mention there may already be defaults. I was trying to look through the src to see if there was a way for me to check or if I can keep those defaults, if any.

Thanks for clarifying. I am glad I had an incorrect assumption.
